# Site settings
title: SDGs data
description: > # this means to ignore newlines until "baseurl:"
  The data candidates behind the upcoming Sutainable Development Goals (SDG).
  This website aggregates and offers the data in raw format, but also
  visualized and open to contributions.
baseurl: "/web" # the subpath of your site, e.g. /blog/
github_username:  SDG-data
# Build settings
markdown: kramdown

gems:
    - jekyll-redirect-from
